/**
 * Interactive market map (Leaflet + OpenStreetMap tiles, loaded via CDN).
 * Reads listing geography/revenue from data/listings.json (generated by
 * scripts/generate_webpage_map_data.py) and tier styling from MAP_CONFIG in data.js.
 */

let LEAFLET_MAP = null;
let MARKER_LAYER = null;
let ALL_LISTINGS = [];
const ACTIVE_TIERS = new Set(["top10", "top25", "bottom75"]);

function initMap() {
  LEAFLET_MAP = L.map("leaflet-map", { scrollWheelZoom: false }).setView(MAP_CONFIG.center, MAP_CONFIG.zoom);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution: "&copy; OpenStreetMap contributors",
    maxZoom: 18,
  }).addTo(LEAFLET_MAP);
  MARKER_LAYER = L.layerGroup().addTo(LEAFLET_MAP);

  fetch(MAP_CONFIG.dataUrl)
    .then((r) => r.json())
    .then((payload) => {
      ALL_LISTINGS = payload.listings;
      renderMapLegend(payload);
      renderMapFilters();
      drawMarkers();
      document.getElementById("map-interpretation").innerHTML = mapInterpretationHtml(payload);
    })
    .catch((err) => {
      document.getElementById("map-interpretation").innerHTML =
        "<p class='map-error'>Map data failed to load (" + err.message + "). Run " +
        "<code>python3 scripts/generate_webpage_map_data.py</code> from the project root, then reload.</p>";
    });
}

function drawMarkers() {
  MARKER_LAYER.clearLayers();
  ALL_LISTINGS.forEach((listing) => {
    if (!ACTIVE_TIERS.has(listing.tier)) return;
    const isFeatured = !!listing.featuredRole;
    const marker = L.circleMarker([listing.lat, listing.lon], {
      radius: isFeatured ? 8 : 5,
      color: isFeatured ? "#111827" : MAP_CONFIG.tierColors[listing.tier],
      weight: isFeatured ? 2 : 1,
      fillColor: MAP_CONFIG.tierColors[listing.tier],
      fillOpacity: isFeatured ? 0.95 : 0.75,
    });
    marker.bindTooltip(markerTooltipHtml(listing), { sticky: true });
    marker.addTo(MARKER_LAYER);
  });
}

function markerTooltipHtml(listing) {
  const roleLabel = listing.featuredRole ? "<br><strong>Featured buy-box comp</strong>" : "";
  return (
    "<strong>" + escapeHtml(listing.title) + "</strong><br>" +
    listing.city + " " + listing.zip + " · " + listing.bedrooms + "BR, sleeps " + listing.sleeps + "<br>" +
    fmtCurrency(listing.revenue) + " revenue · " + fmtCurrency(listing.adr) + " ADR · " + fmtPct(listing.occupancy) + " occ." +
    roleLabel
  );
}

function escapeHtml(s) {
  const d = document.createElement("div");
  d.textContent = s;
  return d.innerHTML;
}

function renderMapLegend(payload) {
  const host = document.getElementById("map-legend");
  host.innerHTML = "<h4>Legend</h4>";
  Object.entries(MAP_CONFIG.tierLabels).forEach(([tier, label]) => {
    const row = document.createElement("div");
    row.className = "legend-row";
    row.innerHTML =
      "<span class='legend-swatch' style='background:" + MAP_CONFIG.tierColors[tier] + "'></span>" + label;
    host.appendChild(row);
  });
  const featuredRow = document.createElement("div");
  featuredRow.className = "legend-row";
  featuredRow.innerHTML = "<span class='legend-swatch legend-swatch--outlined'></span>Featured buy-box comp";
  host.appendChild(featuredRow);
  host.appendChild(
    Object.assign(document.createElement("p"), {
      className: "legend-note",
      textContent: "n=" + payload.n + " reliable-core listings. " + payload.tierNote,
    })
  );
}

function renderMapFilters() {
  const host = document.getElementById("map-filters");
  host.innerHTML = "<h4>Filter</h4>";
  Object.keys(MAP_CONFIG.tierLabels).forEach((tier) => {
    const label = document.createElement("label");
    label.className = "filter-row";
    const cb = document.createElement("input");
    cb.type = "checkbox";
    cb.checked = true;
    cb.addEventListener("change", () => {
      if (cb.checked) ACTIVE_TIERS.add(tier);
      else ACTIVE_TIERS.delete(tier);
      drawMarkers();
    });
    label.appendChild(cb);
    label.appendChild(document.createTextNode(" " + MAP_CONFIG.tierLabels[tier]));
    host.appendChild(label);
  });
}

function mapInterpretationHtml(payload) {
  return (
    "<p>Top-10% and top-25% listings cluster most densely in Seminole and along the northeastern/southwestern " +
    "coordinate clusters identified in Phase 2 geography analysis, while the northern-central cluster and " +
    "ZIP 33755 skew toward the bottom-75% tier. This pattern is descriptive, not causal — Phase 7's adjusted " +
    "analysis found both product mix and a residual geography component implicated, and neither fully explains " +
    "the other. Use this map to sanity-check candidate locations against where top performers already sit, " +
    "not as a standalone geographic thesis.</p>"
  );
}
