/**
 * Leaflet/OpenStreetMap interactive map. Reads webpage/data/listings.json
 * (generated by scripts/generate_webpage_map_data.py from the raw market CSV —
 * do not hand-edit).
 *
 * Two independent filter dimensions, both applied together in drawMarkers():
 *   - ACTIVE_TIERS   — revenue tier (top10 / top25 / bottom75), market-wide.
 *   - ACTIVE_COMPSET — 4BR comp-set category (core / ceiling / counterexample),
 *                      new relative to the reference site. A listing with no
 *                      compSet tag always shows if its tier is active — the
 *                      comp-set filter only ever narrows the "all listings" view.
 *
 * ZIP overlay: webpage/data/listings.json's `zipApprox` array gives one
 * centroid + radius per ZIP, computed directly from that ZIP's own listing
 * coordinates (see scripts/generate_webpage_map_data.py). These are drawn as
 * subtle dashed circles with a ZIP-code label — an approximation, NOT
 * authoritative ZCTA boundary lines. Documented integration point: drop a
 * real `webpage/data/zip-boundaries.geojson` (standard ZCTA polygons) next to
 * listings.json and this file will render it via L.geoJSON instead of the
 * approximate circles — see drawZipOverlay() below.
 */
let LEAFLET_MAP = null;
let MARKER_LAYER = null;
let ZIP_LAYER = null;
let ALL_LISTINGS = [];
let ACTIVE_TIERS = new Set(Object.keys(MAP_CONFIG.tierLabels));
let ACTIVE_COMPSET = new Set(["all"].concat(Object.keys(MAP_CONFIG.compSetLabels)));

function escapeHtml(s) {
  const div = document.createElement("div");
  div.textContent = s == null ? "" : String(s);
  return div.innerHTML;
}

function markerTooltipHtml(listing) {
  let html =
    "<strong>" + escapeHtml(listing.title) + "</strong><br>" +
    escapeHtml(listing.city) + ", VA " + escapeHtml(listing.zip) + " · " + listing.bedrooms + "BR<br>" +
    "Revenue: " + fmtCurrency(listing.revenue) + " · ADR: " + fmtCurrency(listing.adr) +
    (listing.occupancy != null ? " · Occ: " + fmtPct(listing.occupancy) : "");
  if (listing.compLabel) {
    html += "<br><strong>" + escapeHtml(listing.compLabel) + "</strong> (" + escapeHtml(listing.compSet) + ")";
  }
  return html;
}

function drawMarkers() {
  if (!MARKER_LAYER) return;
  MARKER_LAYER.clearLayers();
  ALL_LISTINGS.forEach((listing) => {
    if (!ACTIVE_TIERS.has(listing.tier)) return;
    const compSetActive = ACTIVE_COMPSET.has("all")
      ? true
      : !!(listing.compSet && ACTIVE_COMPSET.has(listing.compSet));
    if (!compSetActive) return;

    const isFeatured = !!listing.compSet;
    const color = isFeatured ? MAP_CONFIG.compSetColors[listing.compSet] : MAP_CONFIG.tierColors[listing.tier];
    const marker = L.circleMarker([listing.lat, listing.lng], {
      radius: isFeatured ? 7 : 4,
      color: isFeatured ? "#16302a" : color,
      weight: isFeatured ? 2 : 1,
      fillColor: color,
      fillOpacity: isFeatured ? 0.95 : 0.65,
    });
    marker.bindTooltip(markerTooltipHtml(listing), { sticky: true });
    MARKER_LAYER.addLayer(marker);
  });
}

function drawZipOverlay(payload) {
  if (!ZIP_LAYER) return;
  ZIP_LAYER.clearLayers();
  // Documented integration point: if a real ZCTA GeoJSON is ever dropped at
  // webpage/data/zip-boundaries.geojson, prefer it over the approximation.
  fetch("data/zip-boundaries.geojson")
    .then((r) => (r.ok ? r.json() : Promise.reject()))
    .then((geojson) => {
      L.geoJSON(geojson, {
        style: { color: "#445752", weight: 1, opacity: 0.45, dashArray: "4 3", fillOpacity: 0.02 },
      }).addTo(ZIP_LAYER);
    })
    .catch(() => {
      // Fallback: approximate ZIP-area circles computed from listing coordinates.
      (payload.zipApprox || []).forEach((z) => {
        const circle = L.circle([z.lat, z.lng], {
          radius: z.radiusDeg * 111000, // rough degrees-to-meters conversion
          color: "#445752",
          weight: 1,
          opacity: 0.35,
          dashArray: "4 4",
          fillOpacity: 0.02,
          interactive: false,
        });
        circle.bindTooltip("ZIP " + z.zip + " (" + z.n + " listings, approximate area)", { sticky: true });
        ZIP_LAYER.addLayer(circle);
        const label = L.marker([z.lat, z.lng], {
          icon: L.divIcon({ className: "zip-label", html: z.zip, iconSize: [40, 14] }),
          interactive: false,
        });
        ZIP_LAYER.addLayer(label);
      });
    });
}

function renderMapLegend(payload) {
  const host = document.getElementById("map-legend");
  if (!host) return;
  let html = "<h4>Revenue tier</h4>";
  Object.keys(MAP_CONFIG.tierLabels).forEach((tier) => {
    html +=
      '<div class="legend-row"><span class="legend-swatch" style="background:' +
      MAP_CONFIG.tierColors[tier] +
      '"></span>' +
      MAP_CONFIG.tierLabels[tier] +
      "</div>";
  });
  html += "<h4>Comp set</h4>";
  Object.keys(MAP_CONFIG.compSetLabels).forEach((key) => {
    html +=
      '<div class="legend-row"><span class="legend-swatch legend-swatch--outlined" style="background:' +
      MAP_CONFIG.compSetColors[key] +
      '"></span>' +
      MAP_CONFIG.compSetLabels[key] +
      "</div>";
  });
  html +=
    '<p class="legend-note">n=' +
    payload.n +
    " listings. " +
    payload.tierNote +
    " ZIP outlines are approximate (centroid + radius from listing coordinates), not authoritative ZCTA boundaries — see map.js for the real-boundary integration point.</p>";
  host.innerHTML = html;
}

function renderMapFilters() {
  const host = document.getElementById("map-filters");
  if (!host) return;
  let html = '<h4>Filter by revenue tier</h4><div class="filter-group" data-filter-group="tier">';
  Object.keys(MAP_CONFIG.tierLabels).forEach((tier) => {
    html +=
      '<label class="filter-row"><input type="checkbox" checked data-tier="' +
      tier +
      '"> ' +
      MAP_CONFIG.tierLabels[tier] +
      "</label>";
  });
  html += '</div><h4>Filter by comp set</h4><div class="filter-group" data-filter-group="compset">';
  html += '<label class="filter-row"><input type="checkbox" checked data-compset="all"> All listings</label>';
  Object.keys(MAP_CONFIG.compSetLabels).forEach((key) => {
    html +=
      '<label class="filter-row"><input type="checkbox" data-compset="' +
      key +
      '"> ' +
      MAP_CONFIG.compSetLabels[key] +
      "</label>";
  });
  html += '</div><h4>ZIP overlay</h4><div class="filter-group"><label class="filter-row"><input type="checkbox" id="zip-overlay-toggle"> Show ZIP areas (approximate)</label></div>';
  host.innerHTML = html;

  host.querySelectorAll('input[data-tier]').forEach((input) => {
    input.addEventListener("change", () => {
      const tier = input.dataset.tier;
      if (input.checked) ACTIVE_TIERS.add(tier);
      else ACTIVE_TIERS.delete(tier);
      drawMarkers();
    });
  });
  host.querySelectorAll('input[data-compset]').forEach((input) => {
    input.addEventListener("change", () => {
      const key = input.dataset.compset;
      if (key === "all" && input.checked) {
        // "All listings" checked resets to showing everything.
        ACTIVE_COMPSET = new Set(["all"].concat(Object.keys(MAP_CONFIG.compSetLabels)));
        host.querySelectorAll('input[data-compset]').forEach((i) => (i.checked = true));
      } else {
        ACTIVE_COMPSET.delete("all");
        host.querySelector('input[data-compset="all"]').checked = false;
        if (input.checked) ACTIVE_COMPSET.add(key);
        else ACTIVE_COMPSET.delete(key);
      }
      drawMarkers();
    });
  });
  const zipToggle = host.querySelector("#zip-overlay-toggle");
  if (zipToggle) {
    zipToggle.addEventListener("change", () => {
      if (!ZIP_LAYER) return;
      if (zipToggle.checked) LEAFLET_MAP.addLayer(ZIP_LAYER);
      else LEAFLET_MAP.removeLayer(ZIP_LAYER);
    });
  }
}

function mapInterpretationHtml(payload) {
  return (
    "<p>Every dot is one listing in the cleaned market dataset, colored by revenue tier; the 4BR core-comp, ceiling-reference, and counterexample properties used in the deep dive below are outlined and colored by comp-set category instead, so they stay visible regardless of the tier filters. " +
    "The market's top 10% (P90 = " +
    fmtCurrency(payload.marketWideThresholds.p90) +
    ") clusters around Rileyville, Stanley, and Shenandoah — the same ZIPs the 4BR deep dive's Location Guidance section flags as priority geography. Use the comp-set filter to isolate just the core comps, or just the ceiling/counterexample properties, against the full market backdrop.</p>"
  );
}

function initMap() {
  const container = document.getElementById("leaflet-map");
  if (!container) return;
  LEAFLET_MAP = L.map(container).setView(MAP_CONFIG.center, MAP_CONFIG.zoom);
  L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
    attribution: "&copy; OpenStreetMap contributors",
    maxZoom: 17,
  }).addTo(LEAFLET_MAP);
  MARKER_LAYER = L.layerGroup().addTo(LEAFLET_MAP);
  ZIP_LAYER = L.layerGroup(); // not added by default; toggled via checkbox

  fetch(MAP_CONFIG.dataUrl)
    .then((r) => r.json())
    .then((payload) => {
      ALL_LISTINGS = payload.listings || [];
      renderMapLegend(payload);
      renderMapFilters();
      drawMarkers();
      drawZipOverlay(payload);
      const interp = document.getElementById("map-interpretation");
      if (interp) interp.innerHTML = mapInterpretationHtml(payload);
    })
    .catch(() => {
      const interp = document.getElementById("map-interpretation");
      if (interp)
        interp.innerHTML =
          '<p class="map-error">Could not load data/listings.json. Run <code>python3 scripts/generate_webpage_map_data.py</code> from the repo root, then reload.</p>';
    });
}
